#!/usr/bin/env node
'use strict';

var LamassuConfig = require('lamassu-config');
var promptly = require('promptly');

var config = new LamassuConfig();

console.log('\nSetting up the Coinmate ticker and trader plugin.\n');
console.log('Please enter your API credentials.\n');
promptly.prompt('ID: ', function(clientIdErr, clientId) {
  promptly.prompt('API Key: ', function(keyErr, key) {
    promptly.password('Secret: ', function(secretErr, secret) {
      promptly.password('Fiat currency (EUR or CZK): ', function(fiatErr, fiatCurrency) {
        updateDb(clientId, key, secret, fiatCurrency, function(err) {
          if (err) throw err;
          console.log('\nSuccess.');
        });
      });
    });
  });
});

function updateDb(clientId, key, secret, fiatCurrency, callback) {
  var newConfig = {
    exchanges: {
      plugins: {
        settings: {
          coinmate: {
            key: key,
            clientId: clientId,
            secret: secret,
            fiatCurrency: fiatCurrency
          }
        },
        current: {
          ticker: 'coinmate',
          trade: 'coinmate',
          wallet: 'coinmate',
          transfer: 'coinmate'
        }
      }
    }
  };
  config.mergeConfig(newConfig, callback);
}
